###############################################
# Report generation for TSQCA
###############################################

#' Generate Markdown Report for QCA Analysis
#'
#' Creates a markdown report from QCA analysis results.
#' Supports two formats: "full" (comprehensive) and "simple" (for manuscripts).
#'
#' @param result A result object from any Sweep function with
#'   \code{return_details = TRUE}.
#' @param output_file Character. Path to output markdown file.
#' @param format Character. Report format: \code{"full"} or \code{"simple"}.
#' @param title Character. Report title.
#'
#' @return Invisibly returns the path to the generated report.
#' @export
#'
#' @examples
#' \donttest{
#' data(sample_data)
#' thrX <- c(X1 = 7, X2 = 7, X3 = 7)
#' 
#' result <- otSweep(
#'   dat = sample_data,
#'   Yvar = "Y",
#'   Xvars = c("X1", "X2", "X3"),
#'   sweep_range = 6:8,
#'   thrX = thrX,
#'   return_details = TRUE
#' )
#' 
#' generate_report(result, "my_report.md", format = "full")
#' }
generate_report <- function(result,
                            output_file = "qca_report.md",
                            format = c("full", "simple"),
                            title = "QCA Analysis Report") {
  
  format <- match.arg(format)
  
  # Validate input
  if (!is.list(result)) {
    stop("'result' must be a list object from a Sweep function.")
  }
  
  if (!"details" %in% names(result)) {
    stop("'result' must contain 'details'. Use return_details = TRUE in Sweep functions.")
  }
  
  # Open file connection
  con <- file(output_file, open = "w", encoding = "UTF-8")
  on.exit(close(con), add = TRUE)
  
  # Write header
  writeLines(paste0("# ", title, "\n"), con)
  writeLines("*(Auto-generated by TSQCA package)*\n", con)
  writeLines(paste0("**Generated**: ", format(Sys.time(), "%Y-%m-%d %H:%M"), "\n"), con)
  writeLines("---\n", con)
  
  # Dispatch to appropriate format
  if (format == "full") {
    write_full_report(result, con)
  } else {
    write_simple_report(result, con)
  }
  
  message("Report generated: ", output_file)
  invisible(output_file)
}


#' Write full report content
#' @keywords internal
write_full_report <- function(result, con) {
  
  summary_df <- result$summary
  details <- result$details
  
  # 1. Summary Table
  writeLines("## 1. Summary Table\n", con)
  writeLines(df_to_md_table(summary_df), con)
  writeLines("\n", con)
  writeLines("---\n", con)
  
  # 2. Detailed Results per Threshold
  writeLines("## 2. Detailed Results\n", con)
  
  for (key in names(details)) {
    det <- details[[key]]
    
    # Determine threshold label
    if (!is.null(det$thrY)) {
      writeLines(paste0("### Threshold Y = ", det$thrY, "\n"), con)
    } else if (!is.null(det$threshold)) {
      writeLines(paste0("### Threshold = ", det$threshold, "\n"), con)
    } else if (!is.null(det$combo_id)) {
      writeLines(paste0("### Combination ", det$combo_id, "\n"), con)
    } else {
      writeLines(paste0("### ", key, "\n"), con)
    }
    
    # X thresholds
    if (!is.null(det$thrX_vec)) {
      thrX_str <- paste(names(det$thrX_vec), det$thrX_vec, sep = "=", collapse = ", ")
      writeLines(paste0("**X Thresholds**: ", thrX_str, "\n"), con)
    }
    
    # Solution
    sol <- det$solution
    if (is.null(sol)) {
      writeLines("**Solution**: No solution\n", con)
    } else {
      # Get all solutions
      n_sol <- get_n_solutions(sol)
      writeLines(paste0("**Number of Solutions**: ", n_sol, "\n"), con)
      
      sol_list <- sol$i.sol$C1P1$solution
      if (!is.null(sol_list)) {
        writeLines("**Solutions**:\n", con)
        for (i in seq_along(sol_list)) {
          expr <- paste(sol_list[[i]], collapse = " + ")
          writeLines(paste0("- M", i, ": ", expr, " -> Y\n"), con)
        }
        writeLines("\n", con)
        
        # Core and peripheral (if multiple solutions)
        if (n_sol > 1) {
          sol_terms <- lapply(sol_list, function(x) {
            unlist(strsplit(paste(x, collapse = " + "), " \\+ "))
          })
          core_terms <- Reduce(intersect, sol_terms)
          all_terms <- Reduce(union, sol_terms)
          peripheral_terms <- setdiff(all_terms, core_terms)
          
          if (length(core_terms) > 0) {
            writeLines(paste0("**Core Conditions**: ", 
                              paste(core_terms, collapse = " + "), "\n"), con)
          } else {
            writeLines("**Core Conditions**: (none - solutions are disjoint)\n", con)
          }
          
          if (length(peripheral_terms) > 0) {
            writeLines(paste0("**Peripheral Terms**: ", 
                              paste(peripheral_terms, collapse = " + "), "\n"), con)
          }
          writeLines("\n", con)
        }
      }
      
      # Metrics
      metrics <- extract_all_metrics(sol$i.sol$C1P1$IC, sol)
      writeLines("**Solution Fit**:\n", con)
      writeLines("| Metric | Value |", con)
      writeLines("|--------|-------|", con)
      writeLines(paste0("| Consistency (inclS) | ", 
                        ifelse(is.na(metrics$sol_inclS), "N/A", 
                               round(metrics$sol_inclS, 3)), " |"), con)
      writeLines(paste0("| PRI | ", 
                        ifelse(is.na(metrics$sol_PRI), "N/A", 
                               round(metrics$sol_PRI, 3)), " |"), con)
      writeLines(paste0("| Coverage (covS) | ", 
                        ifelse(is.na(metrics$sol_covS), "N/A", 
                               round(metrics$sol_covS, 3)), " |"), con)
      writeLines("\n", con)
      
      # Per-term metrics
      if (!is.null(metrics$term_df)) {
        writeLines("**Per-Term Metrics**:\n", con)
        term_df <- metrics$term_df
        # Remove cases column if present (too long)
        if ("cases" %in% names(term_df)) {
          term_df <- term_df[, !names(term_df) %in% "cases", drop = FALSE]
        }
        term_df <- cbind(Term = rownames(term_df), term_df)
        rownames(term_df) <- NULL
        writeLines(df_to_md_table(term_df), con)
        writeLines("\n", con)
      }
    }
    
    writeLines("---\n", con)
  }
  
  # 3. Notes
  writeLines("## Notes\n", con)
  writeLines("- **Core Conditions**: Terms shared across all intermediate solutions.", con)
  writeLines("- **Peripheral Terms**: Terms that appear in some but not all solutions.", con)
  writeLines("- **inclS**: Solution consistency (sufficiency).", con)
  writeLines("- **covS**: Solution coverage.", con)
  writeLines("- **PRI**: Proportional Reduction in Inconsistency.", con)
}


#' Write simple report content
#' @keywords internal
write_simple_report <- function(result, con) {
  
  summary_df <- result$summary
  details <- result$details
  
  # 1. Summary Table
  writeLines("## Summary\n", con)
  writeLines(df_to_md_table(summary_df), con)
  writeLines("\n", con)
  writeLines("---\n", con)
  
  # 2. Solutions Overview
  writeLines("## Solutions Overview\n", con)
  
  for (key in names(details)) {
    det <- details[[key]]
    sol <- det$solution
    
    if (is.null(sol)) next
    
    # Determine threshold label
    if (!is.null(det$thrY)) {
      label <- paste0("Y >= ", det$thrY)
    } else if (!is.null(det$threshold)) {
      label <- paste0("threshold = ", det$threshold)
    } else {
      label <- key
    }
    
    n_sol <- get_n_solutions(sol)
    sol_list <- sol$i.sol$C1P1$solution
    
    if (!is.null(sol_list) && length(sol_list) > 0) {
      writeLines(paste0("### ", label, "\n"), con)
      
      # Show solution formula
      if (n_sol == 1) {
        expr <- paste(sol_list[[1]], collapse = " + ")
        writeLines(paste0("**Solution**: ", expr, " -> Y\n"), con)
      } else {
        writeLines(paste0("**Number of Solutions**: ", n_sol, "\n"), con)
        
        # Core conditions
        sol_terms <- lapply(sol_list, function(x) {
          unlist(strsplit(paste(x, collapse = " + "), " \\+ "))
        })
        core_terms <- Reduce(intersect, sol_terms)
        
        if (length(core_terms) > 0) {
          writeLines(paste0("**Core**: ", paste(core_terms, collapse = " + "), "\n"), con)
        }
        
        # List all solutions briefly
        for (i in seq_along(sol_list)) {
          expr <- paste(sol_list[[i]], collapse = " + ")
          writeLines(paste0("- M", i, ": ", expr, "\n"), con)
        }
      }
      
      # Metrics (brief)
      metrics <- extract_all_metrics(sol$i.sol$C1P1$IC, sol)
      writeLines(paste0("*inclS = ", 
                        ifelse(is.na(metrics$sol_inclS), "N/A", round(metrics$sol_inclS, 3)),
                        ", covS = ",
                        ifelse(is.na(metrics$sol_covS), "N/A", round(metrics$sol_covS, 3)),
                        "*\n"), con)
      writeLines("\n", con)
    }
  }
}